services:
  database:
    image: 'postgres:17'
    restart: unless-stopped
    ports:
      - ${BIND_HOST:-127.0.0.1}:${PORT:-5432}:5432
    env_file:
      - .env
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
